version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - BOT_TOKEN=1832915778:AAEoEWEQLFkG43zhgZ6PfLQyrwci_20_7KE
      - MONGODB_URI=mongodb://mongo:27017/2048-game
      - WEBAPP_URL=https://your-domain.com
      - PORT=3000
      - NODE_ENV=production
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - app-network

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
